/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mapogolions.maybedi;


public class App {
    public static void main(String ...args) {
      System.out.println("Maybe di container");
    }
}