/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mapogolions.maybedi;

import io.github.mapogolions.maybedi.Container;


public class App {
    public static void main(String ...args) {
      System.out.println("Maybe di container");
      Container di = new Container();
      di.putService("database", container -> new Db());
      di.putService("session", container -> new Session());
      di.putService("hero", container -> new Hero("Balto", "1925"));
      di.putService("deps", container -> new Deps((Session) container.getService("session")));
    }
}

class Deps {
  private Session session;
  public Deps(Session session) {
      this.session = session;
  }
}

class Db {}

class Session {}

class Hero {
  public String name;
  public String year;

  public Hero(String name, String year) {
      this.name = name;
      this.year = year;
  }
}