/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.mapogolions.maybedi;

import io.github.mapogolions.maybedi.Container;


public class App {
    public static void main(String ...args) {
      System.out.println("I love this game");
      Container di = new Container();
      di.putService(Db.class, container -> new Db());
      di.putService(Session.class, container -> new Session());
      di.putService(Hero.class, container -> new Hero("Balto", "1925"));
      di.putService(Deps.class, container -> new Deps(container.getService(Session.class)));
    }
}

class Deps {
  private Session session;
  public Deps(Session session) {
      this.session = session;
  }
}

class Db {}

class Session {}

class Hero {
  public String name;
  public String year;

  public Hero(String name, String year) {
      this.name = name;
      this.year = year;
  }
}